[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kwimy-wallflow"
version = "0.1.0"
description = "GTK4 + libadwaita wallpaper picker for matugen"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "Nauris Steins" }
]

[project.scripts]
kwimy-wallflow = "kwimy_wallflow.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["kwimy_wallflow*"]

[tool.setuptools.package-data]
kwimy_wallflow = ["assets/*.css"]
